# Generated by Django 5.2.5 on 2025-09-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_role_user_title_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=models.CharField(blank=True, editable=False, max_length=7, null=True, unique=True),
        ),
    ]
