# Generated by Django 5.2.5 on 2025-09-22 16:07

from django.db import migrations


def assign_student_ids(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    prefix = "stu"
    width = 4

    def next_available(taken_ids, start_number):
        number = start_number
        while True:
            candidate = f"{prefix}{number:0{width}d}"
            if candidate not in taken_ids:
                return candidate, number + 1
            number += 1

    existing_ids_qs = User.objects.exclude(student_id__isnull=True).exclude(student_id="")
    taken = set()
    next_number = 1

    for sid in existing_ids_qs.values_list("student_id", flat=True):
        normalized = sid.strip().lower()
        taken.add(normalized)
        if normalized.startswith(prefix):
            suffix = normalized[len(prefix):]
            if suffix.isdigit():
                next_number = max(next_number, int(suffix) + 1)

    students = User.objects.filter(role="STUDENT").order_by("id")

    for student in students:
        current = student.student_id
        if current:
            normalized = current.strip().lower()
            if normalized != current:
                student.student_id = normalized
                student.save(update_fields=["student_id"])
            if normalized not in taken:
                taken.add(normalized)
                if normalized.startswith(prefix):
                    suffix = normalized[len(prefix):]
                    if suffix.isdigit():
                        next_number = max(next_number, int(suffix) + 1)
            continue

        candidate, next_number = next_available(taken, next_number)
        taken.add(candidate)
        student.student_id = candidate
        student.save(update_fields=["student_id"])


def noop(apps, schema_editor):
    # Nothing to undo safely; leave existing IDs in place.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_student_id"),
    ]

    operations = [
        migrations.RunPython(assign_student_ids, noop),
    ]