# Generated by Django 5.2.5 on 2025-09-18 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('courses', '0001_initial'), ('courses', '0003_course_draft_publish'), ('courses', '0002_enrollment'), ('courses', '0004_merge_0002_0003'), ('courses', '0005_lesson_section_sectionprogress'), ('courses', '0006_lesson_prerequisites'), ('courses', '0007_course_duration_weeks_course_max_students'), ('courses', '0008_lesson_assignments_lesson_credit_points_and_more'), ('courses', '0009_alter_lesson_credit_points'), ('courses', '0010_alter_course_credit_points'), ('courses', '0011_alter_course_credit_points'), ('courses', '0012_alter_course_credit_points_and_more'), ('courses', '0013_delete_sections')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('course_code', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('credit_points', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
                ('is_draft', models.BooleanField(default=True, help_text='If true, the course is a draft and not visible to students')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('duration_weeks', models.PositiveIntegerField(default=12)),
                ('max_students', models.PositiveIntegerField(default=50)),
            ],
            options={
                'db_table': 'course',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_enrolled', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'course'), name='unique_enrollment')],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('learning_objectives', models.TextField(blank=True, help_text='One per line or paragraph')),
                ('reading_list', models.TextField(blank=True, help_text='References or links, one per line')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course')),
                ('prerequisites', models.ManyToManyField(blank=True, help_text='Select lessons that must be completed before this one', related_name='unlocks', to='courses.lesson')),
                ('assignments', models.TextField(blank=True)),
                ('credit_points', models.PositiveIntegerField(default=0)),
                ('duration_hours', models.PositiveIntegerField(default=0)),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to=settings.AUTH_USER_MODEL)),
                ('lesson_code', models.CharField(blank=True, help_text='Lesson ID/Code', max_length=32, null=True)),
            ],
            options={
                'db_table': 'lesson',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.lesson')),
            ],
            options={
                'db_table': 'lesson_section',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SectionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'section_progress',
                'unique_together': {('student', 'section')},
            },
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('course', 'lesson_code'), name='unique_lesson_code_per_course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='credit_points',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='credit_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='SectionProgress',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
