# Generated by Django 5.2.5 on 2025-09-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lesson_section_sectionprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, help_text='Select lessons that must be completed before this one', related_name='unlocks', to='courses.lesson'),
        ),
    ]
