# Generated by Django 5.2.5 on 2025-09-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_lesson_assignments_lesson_credit_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='credit_points',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
