# Generated by Django 5.2.5 on 2025-09-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_lesson_credit_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credit_points',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
