# Generated by Django 5.2.5 on 2025-09-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_course_credit_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credit_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
