# Generated by Django 5.2.5 on 2025-10-11 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_lessonprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_txns', to='courses.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_txns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'credit_transaction',
                'unique_together': {('student', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='LearningMaterialProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='courses.learningmaterial')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'learning_material_progress',
                'unique_together': {('student', 'material')},
            },
        ),
    ]
