# Generated by Django 5.2.5 on 2025-10-11 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_credittransaction_learningmaterialprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonItemProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('reading', 'Reading'), ('assignment', 'Assignment')], max_length=20)),
                ('item_index', models.PositiveIntegerField()),
                ('completed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_progress', to='courses.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_item_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lesson_item_progress',
                'unique_together': {('student', 'lesson', 'section', 'item_index')},
            },
        ),
    ]
