# Generated by Django 5.2.5 on 2025-10-11 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_lessonitemprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.CharField(help_text='Classroom or session name', max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('capacity', models.PositiveIntegerField(default=20)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_schedules', to='courses.lesson')),
            ],
            options={
                'db_table': 'lesson_schedule',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='LessonScheduleEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.lessonschedule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lesson_schedule_enrollment',
                'constraints': [models.UniqueConstraint(fields=('student', 'schedule'), name='unique_schedule_enrollment')],
            },
        ),
    ]
