# Generated by Django 5.2.5 on 2025-10-11 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_lessonschedule_lessonscheduleenrollment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LessonScheduleEnrollment',
        ),
    ]
